services:
  postgres:
    image: postgres:15-alpine
    container_name: online-store-postgres
    restart: always
    environment:
      POSTGRES_DB: onlineStore
      POSTGRES_USER: online_store_app
      POSTGRES_PASSWORD: online_store_app
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: online-store-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-store-app
    restart: always
    ports:
      - '3100:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: 'postgresql://online_store_app:online_store_app@postgres:5432/onlineStore?schema=public'
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data:
