export enum ERROR_CONFLICT_MESSAGE_CODE {
  DUPLICATE_SLUG = 'DUPLICATE_SLUG',
  INVALID_RELATION = 'INVALID_RELATION',
}

export enum ERROR_NOTFOUND_MESSAGE_CODE {
  NOT_FOUND = 'NOT_FOUND',
}

export enum ERROR_UNAUTHORIZED_MESSAGE_CODE {
  UNAUTHORIZED = 'UNAUTHORIZED',
}

export enum ERROR_AUTH_MESSAGE_CODE {
  // 账户状态异常
  STATUS_ERROR = 'STATUS_ERROR',
  // 賬戶已鎖定
  LOCKED = 'LOCKED',
}
